import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

import Titlebar from '../components/Titlebar';
import Intro from './Intro';
import Projects from './Projects';
import Contact from './Contact';


export default function Home() {
  return (
    <div className="bg-white min-h-screen">
      <Head>
        <title>Sanskar Thapa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Titlebar />
      <main className="">
        <section id="Intro" className="snap-start">
          <Intro />
        </section>
        <section id="Project" className="snap-center">
          <Projects />
        </section>
        <section id="Contact" className="snap-end">
          <Contact />
        </section>
      </main>
    </div>
  )
}
