import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState } from 'react';

import Titlebar from '../components/Titlebar';
import Intro from './Intro';
import About from './About';
import Projects from './Projects'; 
import Contact from './Contact';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark": ""}>
      
      <div className="bg-white  h-screen overflow-scroll dark:bg-gray-900">
        <Head>
          <title>Sanskar Thapa</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Titlebar darkMode={darkMode} setDarkMode={setDarkMode}/>
        <main className="dark:bg-gray-900">
          <section id="Intro" className="snap-start">
            <Intro/>
          </section>
          <section id="About" className="snap-center">
            <About/>
          </section>
          <section id="Projects" className="snap-center">
            <Projects/>
          </section>
          <section id="Contact" className="snap-end">
            <Contact/>
          </section>
        </main>
      </div>
    </div>
  )
}
